---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq1-pvc
  labels:
    appname: mq1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbdmirror
  resources:
    requests:
      storage: 5Gi
