apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
  labels:
    appname: mq1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbdmirror
  resources:
    requests:
      storage: 1Gi
